#!/bin/bash
# Usage: download_dir username@destination_server /absolute/folder/path/you/want/to/download /absolute/path/to/the/local
# $1 : username@destination_server
# $2 : /absolute/folder/path/you/want/to/download
# $3 : /absolute/path/to/the/local
rsync --info=progress2 -az $1:$2 $3
